# Site
repository: iacutetres/cv
favicon: images/favicon.ico

# Personal info
name: Enrique Martínez Colomina
title: Analista Programador en Dokuflex
email: iacutetres@gmail.com
website: https://iacutetres.github.io/cv/

# Social links
#twitter_username: iacutetres
#github_username: iacutetres
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: iacutetres
#linkedin_username: emartinezcolomina
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: Info
about_profile_image: images/profileMe.jpg
about_content: | # this will include new lines to allow paragraphs
  Hola, soy Quique, Analista Programador con experiencia destacada en el desarrollo de aplicaciones Java, habilidades avanzadas en Angular, y sólidos conocimientos en el manejo de bases de datos MySQL y MongoDB. 
  A lo largo de mi carrera, he participado en diversos proyectos y he adquirido experiencia en [Git, Maven, Jenkins, Dokers, AWS, API Rest, Hibernate, JPA]. 


# Projects Section
projects_title: Projectos propios

# Experience Section
experience_title: Experiencia

# Education Section
education_title: Educación

# More Section
more_title: Idiomas, cursos y certificaciones
more_content: | # this will include new lines to allow paragraphs
   - 2023 Escuela Oficial de Idiomas : Certificado Inglés B1
   - 2020 IT INSTITUTE : Curso Práctico Architecting on AWS 21h
   - 2019 Universitat Politécnica de Valencia : CURSO ONLINE DE CLOUD COMPUTING CON AMAZON WEB SERVICES (AWS)
   - 2018 Coursera : Introducción a Data Science: Programación Estadística con Lenguaje R


# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

# darkmode: true
